### ISSUE TITLE
Validar el estado de generación de la entrevista

### ISSUE THREAD

**Issue by mancuellofran** [EntrevistadorInteligente/generador-feedback#15]
valida estado generación entrevista y que no permita solicitar multiples veces un feedback

**Comment by RevillaDev** [comment]
Necesito más feedback, por ejemplo.
El endpoint o si es por un listener de kafka la entrada.
Saludos.

**Comment by JamiltonQuintero** [comment]
Señor @Kirenai , buenas. No había visto este mensaje, lo siento.

La idea aquí sería que, una vez el usuario solicita la generación del feedback, actualmente puede enviar infinitos feedbacks, lo que representa un gran riesgo a nivel de seguridad y costos. Este es el endpoint, pero actualmente no cuenta con ningún estado.

Lo mismo ocurre con la colección. Quizás podríamos poner una bandera que indique si se está generando el feedback. No sé, habría que analizar cómo podemos integrarlo con el estado en FG (FEEDBACK_GENERADAS).

Una vez que el microservicio de Python genera la entrevista, podríamos capturar ese evento en este microservicio o simplemente dejarlo como activo. La verdad, no es necesario cambiar esa bandera ya que, de allí en adelante, no debería ser necesaria para otras lógicas.



RespuestaController @PostMapping(value = "/solicitudes-feedback/entrevistas/{idEntrevista}")
![image](https://github.com/user-attachments/assets/b1a29945-5131-42c9-9836-0c63b3481b7e)
![image](https://github.com/user-attachments/assets/06dceaf7-2e76-45f1-bcbc-85ae2a0134b3)

**Comment by RevillaDev** [comment]
Estuve analizando un flujo, donde se agrega al documento feedback en mongo un estado, la petición de entrada al endpoint /solicitudes-feedback/entrevistas/{idEntrevista} debe de tener el estado, para posteriormente obtener el documento y comparar el estado.
Mi duda es, el servicio en python accede al documento feedback en mongo?, si el servicio accede a mongo, puede hacer el cambio del estado de PEDING a COMPLETED.


![Image](https://github.com/user-attachments/assets/18965455-9024-434b-9dc5-b399e1b816c4)

**Comment by JamiltonQuintero** [comment]
Es que ams que completado es dehar un estado pre. De hecho esta el estado que es FG como mencione. Pero necesitamos uno antes o un a babderita que indique que se inicio la generacion del feedback cosa que si nos llega un ataque o el usuario descubre como apretar muchas veces el boton no nos lleguen miles de peticiones al Py si eso pasa se nos va la factura a la v o bueno lo que pasaria es que se come el presupuesto y dejan de responder todas las IAs entonces es algo parecido a lo que describes en el diagrama que sea con FG o GF xD (GENERANDO_FEEDBACK)
