### ISSUE TITLE
Error en guardado entrevista

### ISSUE THREAD

**Issue by JamiltonQuintero** [EntrevistadorInteligente/generador-feedback#22]
@KafkaListener(topics = "preguntasListenerTopic", groupId = "my-group2")

Actualmente, cuando el microservicio de notificaciones se encuentra en reposo, en la primera invocación ocurre un error, por lo que Kafka automáticamente reintenta todo el proceso desde cero. Esto está generando un bug, ya que se insertan dos veces las operaciones y, posteriormente, en las consultas, quedan los registros duplicados y el sistema arroja un error porque encuentra múltiples registros.

Sugerencias:

Envolver las operaciones en una transacción para asegurar que otros escenarios no previstos no transen los registros.
Hacer health checks a los microservicios para que no estén en reposo.
		
![image](https://github.com/user-attachments/assets/828b7b55-a88f-420e-a57e-69cb80621109)
![image](https://github.com/user-attachments/assets/f162b4ae-ff18-462e-bbb4-966f1fc82183)
![image](https://github.com/user-attachments/assets/b1a8e377-9c37-4819-9050-9e15a440e031)
![image](https://github.com/user-attachments/assets/cf580ddb-5f7e-454b-bfbe-60793f715f7e)

**Comment by RevillaDev** [comment]
Se acaba de generar el PR.
El retryWhen se puede filtrar por la excepción ocurrida en el microservicio notifier, para que solo se de retry si el servicio esta apagado o no y evitar que se mande a llamar otra vez en otras execpciones.

Compartir por fa la excepción que se lanza.
